public with sharing class ShelterHomepageController {
    public ShelterHomepageController() {

    }




  public PageReference PetsPage(){
           
            PageReference pageR = new PageReference('http://www.google.com');

            return pageR;
           
            
            



        }


     public PageReference FamilyPage(){
           
            PageReference pageR = Page.NewFamilyPage;

            return pageR;
           
            
            



        }

        public PageReference AdoptPetPage(){
           
            PageReference pageR = new PageReference('http://www.google.com');

            return pageR;
           
            
            



        }
        public PageReference BreedPage(){
           
            PageReference pageR = new PageReference('http://www.google.com');

            return pageR;
           
            
            



        }
        public PageReference DonationPage(){
           
            PageReference pageR = new PageReference('http://www.google.com');

            return pageR;
           
            
            



        }

}